[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "gaitalytics"
dynamic = ["version"]
description = "Add a short description here"
authors = [{name = "André Böni", email = "andre.boeni@llui.org"}]
requires-python = ">= 3.11.0, < 3.12.0"
dependencies = ["pandas", "numpy", "h5py"]

[tool.setuptools_scm]

[project.optional-dependencies]
test = ["pytest", "pytest-cov", "cleanpy"]
build = ["twine", "setuptools", "setuptools_scm", "build", "cleanpy"]
docs = ["sphinx", "sphinx-rtd-theme", "sphinx-autodoc-typehints"]

[tool.pixi.project]
channels = ["conda-forge", "opensim-org"]
platforms = ["win-64"]

[tool.pixi.pypi-dependencies]
gaitalytics = { path = ".", editable = true }

[tool.pixi.dependencies]
opensim = ">=4.5,<5"
ezc3d = ">=1.5.10,<1.6"
pixi-pycharm = ">=0.0.6,<0.1"

# Environments
[tool.pixi.environments]
default = { solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
build = { features = ["build"], solve-group = "default" }
docs = { features = ["docs"], solve-group = "default" }
dev = { solve-group = "test" }

[tool.pixi.feature.docs.tasks]
clean-docs = "cleanpy --include-builds --exclude .pixi ."
docs = "sphinx-build -M html ./docs ./docs/_build -W --keep-going"

[tool.pixi.feature.test.tasks]
clean-test = "cleanpy --include-testing --exclude .pixi ."
test = "pytest -vv --cov=gaitalytics"

[tool.pixi.feature.build.tasks]
clean-build = "cleanpy --include-builds --include-metadata --exclude .pixi ."
build = "python -m build"

[tool.setuptools.packages.find]
include = ["gaitalytics*"]
exclude = ["docs*", "tests*"]



