[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "gaitalytics"
dynamic = ["version"]
description = "Add a short description here"
authors = [{name = "André Böni", email = "andre.boeni@llui.org"}]
requires-python = ">= 3.11.0, < 3.12.0"
dependencies = ["pandas", "numpy", "h5py"]

[tool.setuptools_scm]

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]
build = ["twine"]

[tool.pixi.project]
channels = ["conda-forge", "opensim-org"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tool.pixi.pypi-dependencies]
gaitalytics = { path = ".", editable = true }

[tool.pixi.dependencies]
opensim = ">=4.5,<5"
ezc3d = ">=1.5.10,<1.6"
pixi-pycharm = ">=0.0.6,<0.1"

# Environments
[tool.pixi.environments]
default = { solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
build = { features = ["build"], solve-group = "default" }

[tool.pixi.feature.test.tasks]
test = "pytest -vv --cov=gaitalytics"

[tool.pixi.feature.build.tasks]
build = "python -m build"

[tool.setuptools.packages.find]
include = ["gaitalytics*"]
exclude = ["docs*", "tests*"]



