{% set name = "gaitalytics" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/anboen/gaitalytics/releases/download/v{{ version }}/gaitalytics-{{ version }}.tar.gz
  sha256: de84e7126b9e8d51c937d13c33bfdfa7fa8a626fd55f4735c795f10287068bea
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - pip
  run:
    - python >=3.11
    - h5netcdf >=1.3.0
    - pandas >=1.5
    - pyyaml >=6.0.1
    - scipy >=1.13
    - numpy >=1.23
    - xarray >=2024.6.0
    - pyomeca >=2021.0
    - ezc3d >=1.5.10,*=*python*

test:
  source_files:
    - tests/
  imports:
    - gaitalytics
  commands:
    - pip check
    - pytest ./tests
  requires:
    - pip
    - pytest


about:
  home: https://github.com/anboen/gaitalytics
  summary: This library provides tools to analyze motion capture data.
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - anboen
