{% set name = "gaitalytics" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/anboen/gaitalytics/releases/download/v{{ version }}/gaitalytics-{{ version }}.tar.gz
  sha256: eb54c50ad5f833ae8c38ab74c4c4dcc2be0b6faffef63ca6465e79745b9ffe56
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - pip
  run:
    - python >=3.11
    - h5netcdf >=1.3.0
    - pandas >=1.5
    - pyyaml >=6.0.1
    - scipy >=1.13
    - numpy >=1.23
    - xarray >=2024.6.0
    - pyomeca >=2021.0
    - ezc3d >=1.5.10,*=*python*

test:
  imports:
    - gaitalytics
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/anboen/gaitalytics
  summary: This library provides tools to analyze motion capture data.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anboen
