{ % set name = "gaitalytics" % }
{ % set version = "0.0.0" % }

package:
  name: { { name|lower } }
  version: { { version } }

source:
  git_url: https://github.com/anboen/gaitalytics.git
  git_rev: { { version } }

build:
  noarch: python
  script: { { PYTHON } } -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
  run:
    - python >=3.11
    - h5netcdf >=1.3.0,<1.4
    - pandas >=1.5,<2.3
    - pyyaml >=6.0.1,<6.1
    - scipy >=1.13,<1.15
    - numpy >=1.23,<2.1
    - xarray >=2024.6.0,<2024.7
    - pyomeca = ">=2021.0,<2021.1"
    - ezc3d = ">=1.5.10,<1.6,*python*"

test:
  imports:
    - gaitalytics
  commands:
    - pip check
  requires:
    - pip
    - pytest

about:
  summary: easy gait-metrics for everyone
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anboen
