context:
  name: "gaitalytics"
  version: "0.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: ../dist/gaitalytics-${{ version }}.tar.gz

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.11
    - pip
  run:
    - python >=3.11
    - h5netcdf >=1.3.0
    - pandas >=1.5
    - pyyaml >=6.0.1
    - scipy >=1.13
    - numpy >=1.23
    - xarray >=2024.6.0
    - pyomeca >=2021.0
    - ezc3d >=1.5.10,*=*python*


tests:
  - python:
      imports:
        - gaitalytics
  - files:
      source:
        - tests/
    requirements:
      run:
        - pip
        - pytest
    script:
      - pip check
      - pytest ./tests/test-api.py


about:
  summary: This library provides tools to analyze motion capture data.
  license: MIT
  homepage: https://github.com/anboen/gaitalytics
  repository: https://github.com/anboen/gaitalytics
  documentation: https://pypi.python.org/pypi/imagesize

extra:
  recipe-maintainers:
    - anboen
