schema_version: 1

context:
  name: gaitalytics
  version: ${{ load_from_file("../pyproject.toml").package.version }}

package:
  name: ${{ name }}
  version: ${{ GIT_DESCRIBE_TAG | replace('v', '') }}

source:
  git: https://github.com/anboen/gaitalytics.git

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.11
    - pip
  run:
    - python >=3.11
    - h5netcdf >=1.3.0
    - pandas >=1.5
    - pyyaml >=6.0.1
    - scipy >=1.13
    - numpy >=1.23
    - xarray >=2024.6.0
    - pyomeca >=2021.0
    - ezc3d >=1.5.10,*=*python*

tests:
  - python:
      imports:
        - gaitalytics
  - files:
      source:
        - tests/
    requirements:
      run:
        - pip
        - pytest
    script:
      - pip check
      - pytest tests/test_api.py

about:
  summary: This library provides tools to analyze motion capture data.
  license: MIT
  homepage: https://github.com/anboen/gaitalytics
  repository: https://github.com/anboen/gaitalytics
  documentation: https://pypi.python.org/pypi/imagesize

extra:
  recipe-maintainers:
    - anboen

